spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:mysql://localhost:3306/add_code?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://192.168.1.207:3306/add_code?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    open-in-view: true

qrcode:
  handler: "/upload/**" #前端资源监听路径
  location: "file:E:/img/" #资源存放父目录
  parents: "E:\\img/" #资源存放父目录
#  suffixname: ".png" #生成图片的后缀名称
#  suffix: "png" #生成图片的格式
#  width: 300 #图片的宽
#  height: 300 #图片的高

