spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:mysql://localhost:3306/add_code?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://192.168.1.207:3306/add_code?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true